### PR TITLE
Adding Ticket Viewer

### PR DESCRIPTION
**Pull request by weirdbandkid**
Lets you view ticket transcripts in a web browser.

Let me know is something needs changed, I don't have to latest version of DarkBot.

### CODE REVIEW

**Comment by weirdbandkid** [comment]
@Itz-Hyperz can you review?

**Comment by Itz-Hyperz** [comment]
in your `ticketViewer.js` file, you will need to convert it to only do that app.get when the setup event is triggered, otherwise it won't include the key app.set functions, as those are loaded at the same time or after this extension.

Basically just put the code into a `client.darkbot.on('apiReady', function() { // Your app.get code here })` listener.

**Comment by Itz-Hyperz** [comment]
Also, the documentation for the ticketClose.js file is very confusing, personally I believe it would be better if you just included the individual command inside of this repository for users to be able to reference.

**Comment by Itz-Hyperz** [comment]
And finally, you should check if the file actually exists first, you can do this with `fs.existsSync()` ([here](https://www.geeksforgeeks.org/node-js-fs-existssync-method/)).

**Comment by weirdbandkid** [comment]
Changes have been made.

**Pull request merged**
